### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'init')

### ISSUE THREAD

**Issue by rainyt** [scanline/StrokedTextField#1]
```
Uncaught TypeError: Cannot read properties of null (reading 'init')
    at org_libspark_font_data_RawFont.read (StrokedText.js:84461:14)
    at new StrokedTextField (StrokedText.js:6758:16)
    at DocumentClass.onInit (StrokedText.js:4591:16)
    at DocumentClass.onInitEvent (StrokedText.js:3587:9)
    at DocumentClass.onInitEvent (StrokedText.js:3842:63)
    at DocumentClass.superInitEvent (StrokedText.js:4328:50)
    at DocumentClass.onInitEvent (StrokedText.js:4337:9)
    at DocumentClass.__dispatchEvent (StrokedText.js:1177:15)
    at DocumentClass.__dispatchEvent (StrokedText.js:2025:72)
    at DocumentClass.__dispatchWithCapture (StrokedText.js:2065:15)
```
Hi, some errors have occurred, is there a specification for TTF format? For example, SDF?

**Comment by rainyt** [comment]
<img width="482" alt="image" src="https://github.com/scanline/StrokedTextField/assets/9693090/03f0aa5b-ff84-4a76-95ac-9d979e9f91c4">

**Comment by scanline** [comment]
Possibly a problem with the .ttf font itself and/or your code. Can you share both so I can investigate?

**Comment by rainyt** [comment]
[stroked_textfield_test.zip](https://github.com/scanline/StrokedTextField/files/13184173/stroked_textfield_test.zip)
Yes, This is my running example, and this font is generated through pyftsubset.

**Comment by scanline** [comment]
Looking at the first four bytes of your font 0x4f54544f reveals that it's using PostScript outlines instead
of TrueType, which means that it's actually an .otf and not a .ttf file. This format is not supported by the library (yet).
Meanwhile, however, you can convert your font using e.g. https://www.fontconverter.io/en/otf-to-ttf

**Comment by rainyt** [comment]
Thanks, It's work.
